INSERT INTO grupo (curso_id, docente_id, nombre) 
VALUES 
    (3, 7, 'Matemáticas Básicas'),
    (6, 11, 'Historia del Arte'),
    (9, 15, 'Programación en Python'),
    (12, 21, 'Física Avanzada'),
    (18, 28, 'Literatura Comparada'),
    (25, 36, 'Introducción a la Economía'),
    (32, 42, 'Biología Molecular'),
    (40, 50, 'Diseño Gráfico'),
    (49, 1, 'Desarrollo Web Avanzado'),
    (5, 14, 'Psicología Social'),
    (11, 26, 'Inglés Avanzado'),
    (20, 38, 'Química Orgánica'),
    (28, 48, 'Estadística Aplicada'),
    (38, 6, 'Arquitectura Moderna'),
    (49, 22, 'Marketing Digital'),
    (13, 35, 'Ciencias Políticas'),
    (27, 47, 'Música Contemporánea'),
    (42, 10, 'Inteligencia Artificial'),
    (2, 20, 'Medicina Preventiva'),
    (22, 44, 'Filosofía del Derecho'),
    (43, 3, 'Redes de Computadoras'),
    (7, 18, 'Nutrición y Dietética'),
    (32, 37, 'Teoría Económica'),
    (49, 16, 'Dibujo Técnico'),
    (17, 33, 'Ecología Global'),
    (38, 46, 'Gestión de Proyectos'),
    (11, 2, 'Sociología Urbana'),
    (30, 25, 'Análisis Financiero'),
    (2, 14, 'Cine y Sociedad'),
    (26, 40, 'Robótica Avanzada'),
    (35, 8, 'Ciencias de la Computación'),
    (45, 27, 'Gastronomía Creativa'),
    (6, 7, 'Biotecnología Moderna'),
    (18, 19, 'Arte Digital'),
    (33, 41, 'Psicología del Consumidor'),
    (48, 5, 'Medios de Comunicación'),
    (14, 17, 'Derecho Internacional'),
    (29, 31, 'Biología Marina'),
    (46, 45, 'Turismo Sostenible'),
    (10, 13, 'Lengua y Cultura'),
    (25, 29, 'Geología Aplicada'),
    (43, 43, 'Gestión de Recursos Humanos'),
    (3, 12, 'Investigación Científica'),
    (20, 30, 'Arquitectura de Software'),
    (39, 49, 'Diseño de Moda');
